version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: otushub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - otus_network

  backend:
    build:
      context: ./OtusHub
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
    depends_on:
      postgres:
        condition: service_healthy
      cache:
        condition: service_healthy
    networks:
      - otus_network

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - otus_network
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5

  frontend:
    build:
      context: ./OtusHub-front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - otus_network
    depends_on:
      - backend

networks:
  otus_network:
    driver: bridge

volumes:
  postgres_data:
